//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public string DeliveryBoyName { get; set; }
        public string ProductName { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public int DeliveryBoyId { get; set; }
        public string DeliveryBoyEmail { get; set; }
    
        public virtual User User { get; set; }
    }
}
